### PR TITLE
Update PyYAML requirement

### PR DESCRIPTION
**Pull request by kristian-lesko**
This tool works on Python 2, which the latest PyYAML is not compatible with.

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/153/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/50/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=freeipa-manager-gate-PR47

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-fossa-scanning-zuul-el7/16/ : FAILURE in 1m 20s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-gate/11/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/154/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/47/ : SUCCESS in 18s

**Pull request merged**
