### PR TITLE
Revert "Remove mandatory yamllint dependency"

### PR DESCRIPTION
**Pull request by kristian-lesko**
This reverts commit 2720d4af2ab33d2bd31b26c295175c0c33ea8c61.

The yamllint package turned out not be the issue in the end.

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/131/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/37/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-gate-PR36

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-fossa-scanning-zuul-el7/7/ : FAILURE in 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-gate/2/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/132/ : SUCCESS in 52s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/38/ : SUCCESS in 20s

**Pull request merged**
