### PR TITLE
Dummy PR - do not merge

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/108/ : FAILURE in 39s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/11/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/1/ : SUCCESS in 35s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/2/ : SUCCESS in 36s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/3/ : FAILURE in 2s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/4/ : FAILURE in 6s (non-voting)

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/109/ : FAILURE in 32s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/12/ : SUCCESS in 4s

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/9/ : SUCCESS in 25s (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result - New issues found 
  - 2 BUG
 - 1 CODE_SMELL 

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR31

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/20/ : SUCCESS in 48s (non-voting)

**Comment by nhatking16591** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/21/ : SUCCESS in 46s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/22/ : SUCCESS in 1m 24s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/110/ : FAILURE in 37s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/13/ : SUCCESS in 4s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/23/ : SUCCESS in 1m 16s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/24/ : FAILURE in 7s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/25/ : SUCCESS in 27s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/26/ : SUCCESS in 30s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/27/ : SUCCESS in 37s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/28/ : SUCCESS in 50s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/29/ : SUCCESS in 58s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/14/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/30/ : SUCCESS in 1m 00s (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result
 - 1 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR31

**Comment by caohhung** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/111/ : FAILURE in 22s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/15/ : SUCCESS in 5s

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 1 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR31

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/16/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/34/ : SUCCESS in 47s (non-voting)

**Pull request closed without merging**
