### PR TITLE
Remove yamllint dependency from the repo

### PR DESCRIPTION
**Pull request by kristian-lesko**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/160/ : FAILURE in 36s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/54/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/161/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/55/ : SUCCESS in 9s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=freeipa-manager-gate-PR50

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-fossa-scanning-zuul-el7/19/ : SUCCESS in 1m 57s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-gate/14/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/162/ : SUCCESS in 42s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/50/ : SUCCESS in 36s

**Pull request merged**
