### PR TITLE
Add support for Okta to FreeIPA user sync

### PR DESCRIPTION
**Pull request by kristian-lesko**
Allow using Okta instead of Git config as source for user config.
See individual commit messages for details on implementation.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/120/ : FAILURE in 39s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/28/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/121/ : FAILURE in 42s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/29/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/122/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/30/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - 5 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-gate-PR34

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-fossa-scanning-zuul-el7/5/ : FAILURE in 1m 13s (non-voting)
- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/123/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/36/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/40/ : SUCCESS in 45s (non-voting)

**Pull request merged**
