### PR TITLE
Prepare alerting plugin infrastructure

### PR DESCRIPTION
**Pull request by kristian-lesko**
Prepare infrastructure for dispatching messages to monitoring systems:
* add AlertingPlugin base class; and
* support registering plugins based on settings.

### CODE REVIEW

**Comment by kristian-lesko** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/57/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-opensource-repository-check/1/ : SUCCESS in 10s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/58/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-opensource-repository-check/2/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/59/ : SUCCESS in 1m 11s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-opensource-repository-check/3/ : SUCCESS in 11s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/60/ : SUCCESS in 43s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/17/ : SUCCESS in 24s

**Pull request merged**
