### PR TITLE
Remove mandatory yamllint dependency

### PR DESCRIPTION
**Pull request by kristian-lesko**
Downloading the yamllint package via
PyPI often fails; remove dependency.
This isn't critical for tool itself.

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/124/ : FAILURE in 26s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/31/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/125/ : FAILURE in 27s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/32/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/126/ : FAILURE in 29s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/33/ : SUCCESS in 10s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/127/ : FAILURE in 32s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/34/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/128/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/35/ : SUCCESS in 10s

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-gate-PR35

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-fossa-scanning-zuul-el7/6/ : FAILURE in 1m 09s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-gate/1/ : SUCCESS in 49s
- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/129/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-merge-compliance-check/37/ : SUCCESS in 21s

**Pull request merged**
