### PR TITLE
SETI-5058: Test coverage in sonar

### PR DESCRIPTION
**Pull request by caohhung**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/112/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/17/ : SUCCESS in 4s

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 20 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR32

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/18/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/35/ : SUCCESS in 1m 29s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/113/ : SUCCESS in 41s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/19/ : SUCCESS in 4s

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 20 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR32

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/20/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/36/ : SUCCESS in 1m 20s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/packages/job/freeipa-manager-docker-tox-zuul-el7/114/ : SUCCESS in 1m 25s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/21/ : SUCCESS in 6s

**Comment by yenkins** [comment]
### Sonar scan result
 - 20 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR32

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/22/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/37/ : SUCCESS in 3m 11s (non-voting)

**Comment by caohhung** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - 20 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=freeipa-manager-check-extended-sonar-PR32

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-oss-check/23/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/freeipa-manager-sonarqube-scan-zuul-el7/38/ : SUCCESS in 1m 32s (non-voting)

**Pull request closed without merging**
